apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicasCount | default  "1" }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailableCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
    {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      containers:
        - name: mediaserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bash", "-c", "source /vault/secrets/common && source /vault/secrets/config && mkdir -p /data/studio/hls && chown www-data:www-data /data/studio/hls && /mediaserver-linux-amd64"]
          ports:
            - containerPort: {{ .Values.service.ports.grpc }}
            - containerPort: {{ .Values.service.ports.restapi }}
            - containerPort: {{ .Values.service.ports.ms }}
              protocol: UDP
          env:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_PORT
              value: "6831"
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          volumeMounts:
          - name: {{ .Chart.Name }}-fs
            mountPath: /data/studio
        - name: nginx-rtmp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/nginx-rtmp/sbin/nginx", "-c", "/usr/local/nginx-rtmp/etc/stream-ingester-rtmp.conf", "-g", "daemon off;"]
          ports:
            - containerPort: {{ .Values.service.ports.rtmp }}
          volumeMounts:
          - name: {{ .Chart.Name }}-fs
            mountPath: /data/studio
        - name: nginx-http
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/nginx-rtmp/sbin/nginx", "-c", "/usr/local/nginx-rtmp/etc/stream-ingester-http.conf", "-g", "daemon off;"]
          ports:
            - containerPort: {{ .Values.service.ports.http }}
          volumeMounts:
          - name: {{ .Chart.Name }}-fs
            mountPath: /data/studio
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}
        - name: {{ .Chart.Name }}-fs
          emptyDir: {}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
