replicasCount: 1
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/mediaserver
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalRpcPort: 5090
  internalRpcPort: 5090
  mediaServerPort: "6000"

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

secrets:
  sentryDsn: ""
