replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/mediaserver
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

config:
  USERS_RPC_ADDR: "users.console.svc.cluster.local:5000"
  STREAMS_RPC_ADDR: "streams.console.svc.cluster.local:5102"
  DISPATCHER_RPC_ADDR: "dispatcher.console.svc.cluster.local:5008"
  WEBRTC_SERVER_HOST: "34.66.65.9"
  WEBRTC_SERVER_PORT: "6000"
  RTMP_URL: "rtmp://127.0.0.1:1935/live"
  DATA_DIR: "/data/studio/hls"

service:
  loadBalancerIP:
    webrtc: "34.66.65.9"
    rtmp: "146.148.85.25"
  ports:
    grpc: 5090
    ms: 6000
    rtmp: 1935
    restapi: 8090
    http: 80

resources:
  limits:
   cpu: 2000m
   memory: 2048Mi
  requests:
   cpu: 100m
   memory: 64Mi

autoscaler:
  minCount: 1
  maxCount: 5
  targets:
    targetCPUUtilizationPercentage: 70

api:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 5120m
    hosts:
      - host: console.dev.videocoin.net
        paths:
          - "/api/v1/upload"
          - "/api/v1/sync"
    tls:
      - secretName: tls-cert-console-mediaserver-api
        hosts:
          - console.dev.videocoin.net

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-mediaserver"
  vault.hashicorp.com/agent-inject-secret-common: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config"
  vault.hashicorp.com/agent-inject-secret-config: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/mediaserver/config"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/mediaserver/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
